Umd
ecomplus/passport pull request #8
Opened 2019-08-19 19:14 UTC by talissonf

2019-08-19 23:37 UTC, leomp12 commented on bin/web.js
> +            res.cookie('_passport_' + storeId + '_sig', sig, cookieOptions)
Acho que não precisa gerar este cookie aqui, é para o fluxo de oauth apenas

2019-08-19 23:37 UTC, leomp12 commented on bin/web.js
> +      let id = req.params.id
Parâmetro id me parece desnecessário, pode removê-lo do endpoint inclusive...

2019-08-19 23:37 UTC, leomp12 commented on bin/web.js
> +      let id = req.params.id
Este parâmetro id me parece desnecessário aqui, pode remove-lo inclusive do endpoint

2019-08-19 23:37 UTC, leomp12 commented on routes/api.js
> +      decoded = jwt.decode(accessToken, secret)
Acho que o token já estava sendo decodificado, você não está repetindo o processo?

2019-08-20 11:21 UTC, talissonf commented on routes/api.js
> +      decoded = jwt.decode(accessToken, secret)
Você decodifica ele em um momento mas apenas verifica se o my_id bate com o customer_id e store_id tmb. Mas não exporta o que foi decodificado, só retorna true ou false. 
https://github.com/talissonf/ecomplus-passport/blob/2cbc998e1861e13fe81e7f6ca11b7945960914d3/lib/Auth.js#L51-L52

2019-08-20 11:22 UTC, talissonf commented on bin/web.js
> +      let id = req.params.id
Oukey.

2019-08-20 11:22 UTC, talissonf commented on bin/web.js
> +      let id = req.params.id
Oukey.

2019-08-20 11:22 UTC, talissonf commented on bin/web.js
> +            res.cookie('_passport_' + storeId + '_sig', sig, cookieOptions)
Oukey.

2019-08-20 23:34 UTC, leomp12 commented on routes/api.js
> +      decoded = jwt.decode(accessToken, secret)
Você pode editar a função validate pra passar a retornar o level em vez do booleano, não faz sentido decodificar duas vezes, é um processo caro, perde performance sem necessidade...

2019-08-20 23:39 UTC, leomp12 requested changes
@talissonf o correto é editar a função `validate` no auth pra retornar o level em vez de booleano, possivelmente você vai ter que alterar algo onde a função é chamada, mas evitamos decodificar o token duas vezes.

Após o validate o level retornado deve ser adicionado ao objeto req como `req.authLevel` ou algo do tipo, assim você pode checar o valor nos próximos middlewares.

Acho que a linha de raciocínio é essa...

2019-08-21 15:01 UTC, leomp12 commented
https://github.com/ecomclub/ecomplus-passport/pull/9

2019-08-21 15:01 UTC, closed without merging